name: 'Release'

on:
  push:
    branches:
      - master

jobs:
  semantic:
    name: "Creating Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npx semantic-release
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '12.8.1'
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
